### ISSUE TITLE
ORM: Add Attachment field

### ISSUE THREAD

**Issue by NicoHood** [gtalarico/pyairtable#179]
Hi,
I just saw the ORM feature which looks pretty nice. There is currently no way to get an attachment via ORM.

How do we want to implement this? I think we need to create a new class for airtable attachments that contain all the information required to a) download an attachment b) upload an attachment

**Comment by aleafa** [comment]
The simplest starting point would be to make a read-only (cf. pull request #178) `AttachmentField` class that returned [an array of attachment dictionaries](https://www.airtable.com/developers/scripting/api/cell_values#multiple-attachments).

This class could later be developed to support attachment uploads, which would likely require some way to track the state of the ORM field value, since the data format for uploading attachments to Airtable via API is different than the data format of the attachment dictionaries returned via API. It also appears that the API currently supports _adding_ but not _modifying_ or _removing_ attachments.

Tracking the field state could be as simple as toggling the value of the `read_only` attribute when adding an attachment and formatting the data in the `to_record_value()` method. It could also be more robust, like what is outlined in pull request #159.

The `AttachmentField` class could also be further developed to convert the array of attachment dictionaries into an array of classes. This might benefit state tracking and add flexibility to more easily support changes to Airtable's API.

**Comment by NicoHood** [comment]
That sounds nice!
