### ISSUE TITLE
mypy error: Module "pyairtable" does not explicitly export attribute "Api"; implicit reexport disabled

### ISSUE THREAD

**Issue by noamraph** [gtalarico/pyairtable#202]
I get this when running `mypy --string` on my code:

```
test/init_test.py:16: error: Module "pyairtable" does not explicitly export attribute "Api"; implicit reexport disabled
test/init_test.py:16: error: Module "pyairtable" does not explicitly export attribute "Table"; implicit reexport disabled
```

The relevant line is just:

```
from pyairtable import Api, Table
```

This is how pymongo solved the same issue: https://jira.mongodb.org/browse/PYTHON-3311

**Comment by gtalarico** [comment]
Most common cause for this is having name clashes with other files or packages. Do you have other files or packages named pyairtable?

**Comment by mesozoic** [comment]
This is probably due to missing `__all__` variables in certain places. 

We don't plan to fully support `mypy --strict` until the 2.0.0 release (see [roadmap](249)). Until then you can disable those specific errors with `mypy --strict --implicit-reexport` (read more [here](https://mypy.readthedocs.io/en/stable/config_file.html#confval-implicit_reexport)).
