### ISSUE TITLE
Document new PAT scopes required for each method

### ISSUE THREAD

**Issue by chrowe** [gtalarico/pyairtable#223]
The new Airtable Personal Access Tokens have several scopes you can choose from.
https://airtable.com/developers/web/api/scopes

It would be nice to know which ones are required to use different features of pyairtable . e.g. https://pyairtable.readthedocs.io/en/latest/api.html#interface

**Comment by mesozoic** [comment]
I'm not sure there's a use case for encoding the required scopes into the library, since they can change over time and there's nothing practical the library can do with them. Airtable's API will reject requests if the access token does not have the appropriate scopes, and I don't think pyAirtable should try to do the same. I'm going to close this issue, but pull requests are welcome if there's a valid use case I'm missing.
