### ISSUE TITLE
Implement missing formulas

### ISSUE THREAD

**Issue by MichalKacprzak99** [gtalarico/pyairtable#324]
Hi I want to implement missing formulas from [Airtable Documentation](https://support.airtable.com/docs/formula-field-reference) but I saw [comment](https://github.com/gtalarico/pyairtable/issues/304#issuecomment-1732029360) about need of rethink `formulas` module. Is rethink/redesing in progress?

**Comment by mesozoic** [comment]
Yes, I've got a branch going, but I haven't posted it for review yet. Will try to get that up soon. My general thoughts about it are:

* Formulas should be composable objects, so that a formula can contain other formulas
* We should be able to use operators like `&` and `|` to build complex logical conditions
* Objects representing formulas should only be rendered to `str` at the very end, right before the API call
* We should have a reliable way to represent _every_ Airtable function correctly, without doing each one by hand

Whatever shape this takes, it will almost certainly be a breaking change from the current API.

**Comment by mesozoic** [comment]
See #329 for a proposed redesign.
