### ISSUE TITLE
How to read table from Airtable and get proper data instead of record id reference?

### ISSUE THREAD

**Issue by Mukund50** [gtalarico/pyairtable#393]
I was trying to read table from airtable using below cmd:
**_table = api.table(base_id, table_name)_**

But I am getting reference id from another table as reference instead of actual data in multiple columns.

Below is the example of sample data I am getting:
**_{'id': 'rec00mAMFjd0m0urE',
  'createdTime': '2024-03-27T20:14:28.000Z',
   'Country': ['recADSUI26vTsE1']
}_**

Instead of actually getting the country column value we are getting record id which we will have to use to join with country table to get the actual value. Is there any better way to directly get the country name?

**Comment by mesozoic** [comment]
That's the default behavior of the Airtable API. You can pass `cell_format='string'` to methods like `Table.all()` or `Table.first()`, and the Airtable API will return all fields in string format (which means you'd get the name of the Country record, instead of the record ID). That's not always desirable behavior, though, especially if you need to deal with dates (parsing localized versions is hard) or if you need to look up additional properties of the joined records.

What we often do in our own code is to pre-fetch all records from those "supporting tables" (like a list of countries, for example) at the start of our job, and to store those in memory for easy lookup when iterating over records from other tables. It's usually far more efficient than getting the referenced records individually at the point where you need them. In the 3.0 release (coming soon) the ORM will contain some extra helpers for memoizing those referenced models so that they're already fetched when you interact with the records which reference them. (See #369)

I'm going to close this issue because this is just how the Airtable API works, rather than a bug in the library.
