### ISSUE TITLE
Avoid using relative imports

### ISSUE THREAD

**Issue by OlivierBinette** [gtalarico/pyairtable#413]
I'm getting issues with pyairtable:

<img width="867" alt="image" src="https://github.com/user-attachments/assets/0b5bb34a-fa9c-4d26-9266-1278ccd818ac">

I noticed that relative imports are being used, which seems to be the root of the issue in my case. Relative imports should be avoided in packages:

> Relative imports for intra-package imports are highly discouraged. Always use the absolute package path for all imports. Even now that [PEP 328](http://www.python.org/dev/peps/pep-0328/) is fully implemented in Python 2.5, its style of explicit relative imports is actively discouraged; absolute imports are more portable and usually more readable.

https://github.com/gtalarico/pyairtable/blob/34eb78e5b7b9a348dcf82dd23e53abc611b67e31/pyairtable/__init__.py#L3-L6

**Comment by adamhetherington-dmi** [comment]
I'm experiencing the same issue, scripts are failing as a result

**Comment by bkolasa** [comment]
The same for me

**Comment by mesozoic** [comment]
Thanks for the report! This is the same as #411, a bug in pydantic 2.10.0 and 2.10.1. It was fixed in pydantic 2.10.2. Relative imports are discouraged (and I'll cut a branch to fix them) but they're a red herring here.

Try pinning your project's dependencies to either `pydantic>=2,<2.10` or `pydantic>=2.10.2,<3`. If you still get that error, a minimal code snippet that reproduces the problem would help a lot.
